= Kubernetes Domains - Deepdive
:stylesheet: boot-flatly.css
:nofooter:
:data-uri:
:linkattrs:

In this lab, we will deepdive into the various competency domains within kubernetes.

== Learning Outcomes
After completing the lab, you will be able to understand and use Kubernetes concepts based on use-case scenarios in the following domains:

. Core Concepts
. Configuration
. Multi-Container Pods
. Observability
. Pod Design
. Services & Networking
. State Persistence

=== Start the minikube

. Start minikube locally
`minikube start --driver=virtualbox`

. Verify the kubectl context `kubectl config get-contexts` is set to minikube. If not, set it to minikube `kubectl config use-context minikube`

== Pods 
=== Advanced Configuration & Custom Commands

. Scenarios
[%collapsible]
====
These are the scenarios
====

. Create a busybox pod which prints "Hello from pages Yellow Pages" on the console
. Create a busybox pod which prints "Hello from pages Yellow Pages" on the console, for every 10 seconds infinitely
. Create an nginx pod and test it in the browser
. Create a busybox pod which prints the output of nginx pod for every 10 seconds

. Create a busybox pod which prints the `current date` on the console  - Instructions
. Create a busybox pod which prints `current date` on the console, for every 10 seconds infinitely  - Instructions
. Create an nginx pod and test it in the browser  - Instructions
. Create a busybox pod which prints the output of `pages application` for every 10 seconds infinitely  - Instructions

=== Environment variables:

. Create environment variables for busybox pod with key=`course` and value=`K8s`
    Verify the environment variables are set properly
. Create environment variables for pages application with key=`PAGE_CONTENT` and value=`Hello from pages environment`
    Verify the environment variables are set properly  - Instructions 

=== Probes and Observability:


. Create a simple web server that starts serving traffic after some delay while the application starts up. If we didn't configure our
readiness probe, Kubernetes would either start sending traffic to the container before we're ready, or it would mark the pod as unhealthy and never send it traffic. Use the image `python:2.7-alpine`

. In the previous scenario add a liveness probe of type exec command to check if index.html exists whose exit code determines the sucess of the probe.

. Configure liveness and readiness probe for pages application and verify - Instructions

== Volumes

== SecurityContext
. Create a pod with a container that writes the current date to a file in a mounted volume at /etc/kal-directory/date-file.txt every five seconds. The created file should have the user ID 45 and the group ID 231 which will be useful for auditing and tracking files system updates. Use alpine image.

=== Multi-Container Pod Design patterns
. Create a pod that defines an application container which writes the current date to a log file every five seconds. The sidecar container is nginx serving that log file in a shared directory.
. Create a pod that defines the pages application container which writes the logs to a file. Create a sidecar container serving that log file in a shared directory - Instructions
. Create a pod that defines an application container which writes the current date and memory usage to a log file every five seconds. The adapter container will inspect the contents of the app's log file, reformat it, and write the correctly formatted output to a new file

+
HINT: `free -tw --giga`

+
Adapter Input Sample

+
[source, java]
-------------
Thu Mar 4 11:26:28 GMT 2021
              total        used        free      shared     buffers       cache   available
Mem:             32           9          10           0           0          11          22
Swap:             2           0           2
Total:           34           9          12
-------------

+
Adapter Output Sample

+

[source, java]
-------------
Date: Thu Mar  4 09:36:42 UTC 2021
Total Memory: 34GB
Free Memory: 12GB
-------------


. Create a pod that defines an application container which writes the proccess to a file every five seconds. Create a adapter container that display the top 3 processes consuming maximum memory. 

+
HINT: `ps -ao "user,comm,pid,pcpu,pmem,start,time" --sort=pmem`
+
Sample Output

+
[source, java]
-------------
USER     COMMAND           PID %CPU %MEM  STARTED     TIME
student  java            16213  2.7  3.7 07:34:42 00:06:47
student  gnome-shell      2373 21.7  1.7   Feb 22 2-04:02:42
student  chrome          14101  1.3  1.1 13:09:55 00:17:56
-------------

=== Labels, Selectors and Annotations

. Add a label `tier=service` to the pages application and display the label
. Create a pod nginx and add a label `tier=frontend` 
. Get all the pods with label `tier=frontend`
. Get all the pods which has label tier set to any value
. Create a service which routes the request to nginx pod using selectors in the yaml file
. Annotate nginx pod with annotation `team=yourteam` and `course=k8s`

=== Deployments

. Create pages deployment with 2 replicas imperatively
. Create pages deployment with 2 replicas using yaml manifest file
. Verify the first version of deployment has been deployed and rolled out
. Update the manifest to use 3 replicas and image to use the latest version [TODO]
. Verify the second version of deployment has been deployed and rolled out
. Rollback to the previous version
. Manually scale to use 5 replicas
. Manually scale to use 1 replica

=== Services

. Create a service (color) of type nodeport and expose port 8080 and target port 80, with the selector app=colorful
. Create an nginx deployment which prints echo Green > /usr/share/nginx/html/index.html & expose on port 80 and label app=colorful
. Create an nginx deployment which prints echo "Color: Blue" > /usr/share/nginx/html/index.html & expose on port 80 label app=colorful

=== Persistent Volumes

. Create a Persistent Volume which is used as a long term storage solution. Create a Persistent Volume Claim to use the persistent volume. Create a pod that defines an application container which writes the current date to a log file every five seconds and this pod will eventuall use persistent volume claim when mounting the log file to persistent volume.

. Refactor question number 4 of Multicontainer section to mount the files on Persistent Volume. Create required Persistent Volume and Persistent Volume Claim. Storage capacity of Persistent Volume shoud not exceed 500M - Instructions

. Create a pod that writes Pages application logs to a log file. Create a Persistent Volume and Persistent Volume claim to mount the pages application log file. - Instructions

=== Configmaps and Secrets

. Create a ConfigMap from literal values with key='course' and value='k8s' imperatively. Create environment variables for nginx pod with key=`course` and value to be read from the configmap.
Hint: `configMapKeyRef`
. Create a ConfigMap from literal values with key='PAGE_CONTENT' and value='Hello from pages environment' imperatively. Create environment variables for pages aplication with key=`PAGE_CONTENT` and value to be read from the configmap. - Instructions
. Create the above ConfigMap using yaml. Create a nginx pod and read the environment variables key and value from ConfigMap
hint: configMapRef
. Create the above ConfigMap using yaml. Create a nginx pod and read the environment variables key and value from ConfigMap. - Instructions
. Create a ConfigMap from a properties file with key='course' and value='k8s' imperatively. Create a nginx pod and mount the configmap as a volume.
. Create a configMap from application.properties used by Pages application. Mount this configmap as a volume while creating pod for pages application - Instructions

. Create a secret from literal value with key='my-token' and value=base 64 encoded value of 'token-e8ujdekdjueke' imperatively. Create environment variable for nginx pod with key='my-token' and value to be read from the secret.
Hint: `secretMapKeyRef`

. Create a secret from literal values with key='password' and value=base 64 encoded value of 'admin@123' imperatively. Create environment for Pages application with key='password' and value to be read from the secret. - Instructions

. Create the above secret from a properties file with key='password' and value=base 64 encoded value of 'admin@123'. Mount this secret as a volume while creating an nginx pod. - Instructions

=== Jobs and CronJobs

. Create a service (color) of type nodeport and expose port 8080 and target port 80, with the selector app=colorful
. Create an nginx deployment which prints echo Green > /usr/share/nginx/html/index.html & expose on port 80 and label app=colorful
. Create an nginx deployment which prints `echo "Color: Blue" > /usr/share/nginx/html/index.html` & expose on port 80 label `app=colorful`

. Create a job to print current date and time

. Create a job to calculate the value of pi upto 1000 digits and print the output in command line. Use Perl to calculate.

. Create a job which runs a workload which simulates rolling the dice and returns a zero exit code (i.e. success) when you get a six.

. Create a CronJob that will ping Github every minute and check that their site hasn't gone down. You can use alpine image.

+

`image: alpine`

+ 

`command: ["/bin/sh"]`
+
`args: ["-c", "ping -w 1 github.com"]`

. Create a cron job to print current date and time every minute

. Create a cron job to print "Time: 3.30 pm. It is break time. Lets stretch out a bit or have a coffee!" at 3.30pm today 

=== Namespaces & ResourceQuotas

. Create a namespace called alpha imperatively & declaratively


. Create a namespace called angel declaratively & declaratively



. Create a resource quota in the namespace alpha with the below requirement. After creating the quota, Create an nginx pod within alpha and should you get an error, try to troubleshoot and solve it

+
[source, yaml]
-------------
pods:5    
"requests.cpu": "2"
"requests.memory": 1024m
"limits.cpu": "4"
"limits.memory": 2048m
-------------



=== NetworkPolicy

=== ServiceAccount